service:
  port: 9091
  port-grpc: 9090
db:
  portgres:
    username: "root"
    password: "secret"
    host: "localhost"
    port: 5432
    min-open: 10
    max-open: 100
    max-life-time: 12s
    keep-alive-interval: 20s

